version: "3"

services:
  db:
    container_name: monorepo-mongo
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  mongo-express:
    container_name: monorepo-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8082
    env_file:
      - .env
  redis:
    container_name: monorepo-redis
    image: "redis:alpine"
    ports:
      - 6379:6379
  redis-commander:
    container_name: monorepo-redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "8081:8081"
  elasticsearch:
    container_name: monorepo-elastic-search
    image: elasticsearch:8.1.3
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - .env
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.templates.enabled: "true"
      xpack.security.enabled: "false"
  kibana:
    container_name: monorepo-kibana
    image: kibana:8.1.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    env_file:
      - .env
  jaegertracing:
    container_name: monorepo_jaegertracing
    image: jaegertracing/all-in-one:latest
    env_file:
      - .env
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
