version: "3"

services:
  db:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - db
    ports:
      - 8082:8082
    env_file:
      - .env
